In [1]:
import numpy as np
from sklearn.model_selection import KFold

In [12]:
# genrating random values(independent features)
X= np.random.random(size= (25,5))

# genrating random interger values (dependent features)
Y=np.random.randint(low=0, high=2, size= 25)

In [13]:
Y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1])

In [47]:
#Creating a class
kf = KFold( n_splits= 6, shuffle= True)

# Generate indices to split data into training and test set.
for train_index, test_index in kf.split(X):  
    print(train_index, test_index) # training and testing set indices for that split.

[ 0  1  2  3  4  5  6  7  9 10 11 12 13 14 15 17 19 21 23 24] [ 8 16 18 20 22]
[ 1  2  3  5  6  7  8  9 10 12 13 15 16 17 18 19 20 21 22 23 24] [ 0  4 11 14]
[ 0  1  3  4  5  6  7  8  9 10 11 13 14 16 17 18 20 21 22 23 24] [ 2 12 15 19]
[ 0  1  2  4  5  6  7  8 11 12 13 14 15 16 18 19 20 21 22 23 24] [ 3  9 10 17]
[ 0  2  3  4  6  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 24] [ 1  5  7 23]
[ 0  1  2  3  4  5  7  8  9 10 11 12 14 15 16 17 18 19 20 22 23] [ 6 13 21 24]


***what to do in case of unequal proportions of test data***

> That time we do `Stratified Sampling`

> Here we make sure that class or features of our training and testing dataset contains data in equal proportions as it is in the original dataset. 

> For example if our data contains two type of class in 3:2 ratio, then our test, train dataset should also contain those two types of class in 3:2 ratio.  

***`cross_val_score()`***

In [56]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

In [54]:
from sklearn import datasets
data = datasets.load_iris()

x = data['data']   
y = data['target'] # output features

In [57]:
# model building
knn  = KNeighborsClassifier(n_neighbors= 5)
scores = cross_val_score (knn, x,y,
                          cv= 10, # no of folds (whole data in 10 parts and train each part on the knn model and check accuracy)
                          scoring= 'accuracy')
scores

array([1.        , 0.93333333, 1.        , 1.        , 0.86666667,
       0.93333333, 0.93333333, 1.        , 1.        , 1.        ])

In [58]:
# now taking the mean of those accuracy
scores.mean()

0.9666666666666668

***What is the optimum value of th parameter `n_neighbors` of KNN model for which the accuracy mean is maximum***

In [62]:
for i in range(1,30):
    knn  = KNeighborsClassifier(n_neighbors= i)
    scores = cross_val_score (knn, x,y,
                          cv= 10, # no of folds (whole data in 10 parts and train each part on the knn model and check accuracy)
                          scoring= 'accuracy')
    print(i, scores.mean())

1 0.96
2 0.9533333333333334
3 0.9666666666666666
4 0.9666666666666666
5 0.9666666666666668
6 0.9666666666666668
7 0.9666666666666668
8 0.9666666666666668
9 0.9733333333333334
10 0.9666666666666668
11 0.9666666666666668
12 0.9733333333333334
13 0.9800000000000001
14 0.9733333333333334
15 0.9733333333333334
16 0.9733333333333334
17 0.9733333333333334
18 0.9800000000000001
19 0.9733333333333334
20 0.9800000000000001
21 0.9666666666666666
22 0.9666666666666666
23 0.9733333333333334
24 0.96
25 0.9666666666666666
26 0.96
27 0.9666666666666666
28 0.9533333333333334
29 0.9533333333333334


> Hence `n_neighbors`=13,18,20 gives high CV value